// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh0fiplLXvR1WhiJTquE5EI1sQf0sAOAk',
    appId: '1:41110923671:android:f8ef175dea6399b7237cd2',
    messagingSenderId: '41110923671',
    projectId: 'tunga-app-2026',
    storageBucket: 'tunga-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvvzDFNdeQw6J_uUR-hYtt5o1rYY87KfU',
    appId: '1:41110923671:ios:dda5a75c8d52fd48237cd2',
    messagingSenderId: '41110923671',
    projectId: 'tunga-app-2026',
    storageBucket: 'tunga-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.tunga',
  );

  // Registered for the Admin Web dashboard (lib/admin_main.dart) — a
  // separate Firebase Web app from the mobile Android/iOS apps above,
  // since it's a different deployment target with its own origin.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByB9E6Yo1U_v0_2_ajjMa_Af0tmM7LPWc',
    appId: '1:41110923671:web:dd1a975aa1503dad237cd2',
    messagingSenderId: '41110923671',
    projectId: 'tunga-app-2026',
    authDomain: 'tunga-app-2026.firebaseapp.com',
    storageBucket: 'tunga-app-2026.firebasestorage.app',
  );
}
